version: "3"
services:
  web:
    # replace username/repo:tag with your name and image details
    image: localhost:5000/webcontainer:V_0.6
    deploy:
      replicas: 5
      resources:
        limits:
          cpus: "0.1"
          memory: 50M
      restart_policy:
        condition: on-failure
    ports:
      - "80:80"
    networks:
      - webnet
networks:
  webnet:
